export const FETCH_DATA = "FETCH_DATA";

export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";

export const ADD_CARD_REQUEST = "ADD_CARD_REQUEST";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";

export const EDIT_CARD_REQUEST = "EDIT_CARD_REQUEST";
export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS";

export const ADD_LIST_REQUEST = "ADD_LIST_REQUEST";
export const ADD_LIST_SUCCESS = "ADD_LIST_SUCCESS";

export const ADD_DESCRIPTION_REQUEST = "ADD_DESCRIPTION_REQUEST";
export const ADD_DESCRIPTION_SUCCESS = "ADD_DESCRIPTION_SUCCESS";

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";

export const EDIT_LIST_REQUEST = "EDIT_LIST_REQUEST";
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";

export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";

export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";

export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS";

export const DELETE_LABEL_REQUEST = "DELETE_LABEL_REQUEST";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";

export const ADD_EXDATE_REQUEST = "ADD_EXDATE_REQUEST";
export const ADD_EXDATE_SUCCESS = "ADD_EXDATE_SUCCESS";

export const DELETE_EXDATE_REQUEST = "DELETE_EXDATE_REQUEST";
export const DELETE_EXDATE_SUCCESS = "DELETE_EXDATE_SUCCESS";

export const END_EXDATE_REQUEST = "END_EXDATE_REQUEST";
export const END_EXDATE_SUCCESS = "END_EXDATE_SUCCESS";

export const ADD_FILE_REQUEST = "ADD_FILE_REQUEST";
export const ADD_FILE_SUCCESS = "ADD_FILE_SUCCESS";

export const ADD_GROUND_REQUEST = "ADD_GROUND_REQUEST";
export const ADD_GROUND_SUCCESS = "ADD_GROUND_SUCCESS";

export const DELETE_GROUND_REQUEST = "DELETE_GROUND_REQUEST";
export const DELETE_GROUND_SUCCESS = "DELETE_GROUND_SUCCESS";

export const MOVE_CARD_REQUEST = "MOVE_CARD_REQUEST";
export const MOVE_CARD_SUCCESS = "MOVE_CARD_SUCCESS";

export const CLONE_CARD_REQUEST = "CLONE_CARD_REQUEST";
export const CLONE_CARD_SUCCESS = "CLONE_CARD_SUCCESS";

export const SAVE_CARD_REQUEST = "SAVE_CARD_REQUEST";
export const SAVE_CARD_SUCCESS = "SAVE_CARD_SUCCESS";

export const UNSAVE_CARD_REQUEST = "UNSAVE_CARD_REQUEST";
export const UNSAVE_CARD_SUCCESS = "UNSAVE_CARD_SUCCESS";

export const COLLECT_ACTION_CARD_SUCCESS = "COLLECT_ACTION_CARD_SUCCESS";
