export const GET_BOARDS_REQ = "GET_BOARDS_REQ";
export const GET_BOARDS_SUCCESS = "GET_BOARDS_SUCCESS";

export const GET_DETAIL_BOARD_REQ = "GET_DETAIL_BOARD_REQ";
export const GET_DETAIL_BOARD_SUCCESS = "GET_DETAIL_BOARD_SUCCESS";
