export const ADD_WIN_STATUS_REQUEST = "ADD_WIN_STATUS_REQUEST";
export const ADD_WIN_STATUS_SUCCESS = "ADD_WIN_STATUS_SUCCESS";

export const ADD_LOSE_STATUS_REQUEST = "ADD_LOSE_STATUS_REQUEST";
export const ADD_LOSE_STATUS_SUCCESS = "ADD_LOSE_STATUS_SUCCESS";

export const ADD_MOVETO_STATUS_REQUEST = "ADD_MOVETO_STATUS_REQUEST";
export const ADD_MOVETO_STATUS_SUCCESS = "ADD_MOVETO_STATUS_SUCCESS";

export const ADD_DELETE_STATUS_REQUEST = "ADD_DELETE_STATUS_REQUEST";
export const ADD_DELETE_STATUS_SUCCESS = "ADD_DELETE_STATUS_SUCCESS";
